# Generated by Django 4.1.6 on 2023-07-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fileTable',
            fields=[
                ('fileId', models.AutoField(primary_key=True, serialize=False)),
                ('fileType', models.CharField(max_length=100)),
                ('fileName', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='documents/')),
                ('deviceId', models.CharField(max_length=250)),
                ('converted', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
